// Sync contract ABIs from the iris-core Foundry build output into typed TS modules.
//
// Generates one `*.ts` module per vendored contract (ABI exported `as const` so
// viem can infer types), plus a merged `errors.ts` decoder that folds together
// every custom error that can surface from the Iris stack — protocol + venue
// adapters + the dependency errors that propagate through the adapters (solady
// transfer/clone helpers and Aave's custom protocol errors) — so a single ABI
// can decode any such revert. (Morpho Blue reverts with Error(string), which viem
// decodes natively, so it contributes no custom-error ABI.)
//
// Behaviour: all-or-nothing. Every required artifact is loaded and validated
// before anything is written, and the output dir is cleared of generated files
// first, so the result is a pure function of FULL_ABIS + the artifacts (no stale
// orphans, no half-written tree on failure).
//
// Usage:
//   IRIS_CORE_OUT=/abs/path/to/iris-core/out pnpm --filter @iris-credit/core-sdk sync:abis
//
// IRIS_CORE_OUT defaults to a sibling `iris-core-internal` checkout next to the
// repo root. iris-core is a separate (private) repo, so the path is configurable.

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const repoRoot = resolve(pkgRoot, "..", "..");
const abisDir = resolve(pkgRoot, "src", "abis");

const IRIS_CORE_OUT =
  process.env.IRIS_CORE_OUT ?? resolve(repoRoot, "..", "iris-core-internal", "out");
const IRIS_CORE_ROOT = resolve(IRIS_CORE_OUT, "..");

// Full ABIs to vendor: { export name, source file dir, contract name, output file }.
const FULL_ABIS = [
  { exportName: "irisAbi", file: "Iris.sol", name: "Iris", out: "iris.ts" },
  { exportName: "blmAbi", file: "Blm.sol", name: "Blm", out: "blm.ts" },
  { exportName: "whitelistBlmAbi", file: "WhitelistBlm.sol", name: "WhitelistBlm", out: "whitelist-blm.ts" },
  { exportName: "aaveV3AdapterAbi", file: "AaveV3Adapter.sol", name: "AaveV3Adapter", out: "aave-v3-adapter.ts" },
  { exportName: "morphoBlueAdapterAbi", file: "MorphoBlueAdapter.sol", name: "MorphoBlueAdapter", out: "morpho-blue-adapter.ts" },
];

// Error-only sources folded into the merged `errorsAbi` — dependency contracts whose
// custom-error reverts propagate through the adapters/Iris to an SDK consumer, but
// whose full ABI we don't vendor. Optional: skipped with a warning if absent.
const ERROR_SOURCES = [
  { file: "SafeTransferLib.sol", name: "SafeTransferLib", label: "solady transfer/approve/permit2 errors" },
  { file: "LibClone.sol", name: "LibClone", label: "solady clone (pod) deployment errors" },
  { file: "Errors.sol", name: "Errors", label: "Aave V3 (aave-v3-origin) protocol errors" },
];

function loadArtifact(file, name, { required }) {
  const path = resolve(IRIS_CORE_OUT, file, `${name}.json`);
  let raw;
  try {
    raw = readFileSync(path, "utf8");
  } catch (err) {
    if (required) throw new Error(`Required artifact not found: ${path}\n  ${err.message}`);
    console.warn(`  ! skipped optional source (not found): ${file}/${name}.json`);
    return null;
  }
  let json;
  try {
    json = JSON.parse(raw);
  } catch (err) {
    throw new Error(`Artifact is not valid JSON: ${path}\n  ${err.message}`);
  }
  if (!Array.isArray(json.abi)) {
    throw new Error(`Artifact has no \`abi\` array: ${path}`);
  }
  return json;
}

// Resolve the iris-core solc version + git commit for provenance stamping.
function resolveProvenance(sampleArtifact) {
  const solc = sampleArtifact?.metadata?.compiler?.version ?? "unknown";
  let commit = "unknown";
  try {
    commit = execFileSync("git", ["-C", IRIS_CORE_ROOT, "rev-parse", "--short", "HEAD"], {
      encoding: "utf8",
    }).trim();
    const dirty = execFileSync("git", ["-C", IRIS_CORE_ROOT, "status", "--porcelain"], {
      encoding: "utf8",
    }).trim().length > 0;
    if (dirty) commit += "-dirty";
  } catch {
    // iris-core isn't a git checkout, or git is unavailable — leave commit "unknown".
  }
  return `iris-core @ ${commit} (solc ${solc})`;
}

let PROVENANCE = "iris-core @ unknown";

function banner(lines) {
  return [
    "// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit by hand.",
    ...lines.map((l) => `// ${l}`),
    `// Provenance: ${PROVENANCE}`,
    "// Regenerate: pnpm --filter @iris-credit/core-sdk sync:abis",
    "",
    "",
  ].join("\n");
}

function emitConst(exportName, value, bannerLines) {
  return `${banner(bannerLines)}export const ${exportName} = ${JSON.stringify(value, null, 2)} as const;\n`;
}

// Canonical ABI type, expanding tuples to their flattened component form so the
// dedup key matches the real Solidity error selector (e.g. Foo((address,uint256))
// rather than Foo(tuple)).
function canonicalType(input) {
  if (input.type.startsWith("tuple")) {
    const inner = (input.components ?? []).map(canonicalType).join(",");
    return `(${inner})${input.type.slice("tuple".length)}`;
  }
  return input.type;
}

function errorSignature(item) {
  return `${item.name}(${(item.inputs ?? []).map(canonicalType).join(",")})`;
}

// --- 1) Load + validate every required artifact BEFORE touching the tree. ---
const fullArtifacts = FULL_ABIS.map((spec) => ({
  spec,
  abi: loadArtifact(spec.file, spec.name, { required: true }).abi,
}));

const firstArtifact = loadArtifact(FULL_ABIS[0].file, FULL_ABIS[0].name, { required: true });
PROVENANCE = resolveProvenance(firstArtifact);

console.log(`Syncing ABIs from ${IRIS_CORE_OUT}`);
console.log(`Provenance: ${PROVENANCE}`);

// --- 2) Build the merged error set (protocol + dependency sources). ---
const errorBag = new Map(); // signature -> error fragment
let totalErrors = 0;

const outputs = new Map(); // filename -> file content

for (const { spec, abi } of fullArtifacts) {
  outputs.set(spec.out, emitConst(spec.exportName, abi, [`Source: iris-core out/${spec.file}/${spec.name}.json`]));
  const errs = abi.filter((i) => i.type === "error");
  for (const e of errs) errorBag.set(errorSignature(e), e);
  totalErrors += errs.length;
  console.log(`  ✓ ${spec.out.padEnd(24)} (${abi.length} entries, ${errs.length} errors)`);
}

const errorSourceLabels = [];
for (const src of ERROR_SOURCES) {
  const art = loadArtifact(src.file, src.name, { required: false });
  if (!art) continue;
  const errs = art.abi.filter((i) => i.type === "error");
  for (const e of errs) errorBag.set(errorSignature(e), e);
  totalErrors += errs.length;
  errorSourceLabels.push(`out/${src.file}/${src.name}.json — ${src.label} (${errs.length} errors)`);
  console.log(`  ✓ ${(src.name + " errors").padEnd(24)} (${errs.length} errors)`);
}

// Deterministic (codepoint) sort so regeneration is byte-stable.
const mergedErrors = [...errorBag.values()].sort((a, b) => {
  const x = errorSignature(a);
  const y = errorSignature(b);
  return x < y ? -1 : x > y ? 1 : 0;
});

outputs.set(
  "errors.ts",
  emitConst("errorsAbi", mergedErrors, [
    "Merged custom errors for decoding reverts from the Iris stack.",
    "Protocol + venue adapters: Iris, Blm, WhitelistBlm, AaveV3Adapter, MorphoBlueAdapter.",
    "Dependency errors that propagate through the adapters:",
    ...errorSourceLabels.map((l) => `  ${l}`),
    `Deduped by selector: ${totalErrors} collected -> ${mergedErrors.length} unique.`,
    "Note: Morpho Blue reverts with Error(string) (decoded natively by viem), so it has",
    "no custom-error ABI; Aave V3 (aave-v3-origin) uses custom errors, included above.",
  ]),
);
console.log(`  ✓ ${"errors.ts".padEnd(24)} (${mergedErrors.length} unique errors)`);

// --- 3) Barrel. ---
const barrelExports = [...FULL_ABIS.map((a) => a.out), "errors.ts"].map(
  (f) => `export * from "./${f.replace(/\.ts$/, ".js")}";`,
);
outputs.set("index.ts", `${banner(["Barrel for the generated contract ABIs."])}${barrelExports.join("\n")}\n`);

// --- 4) Clear generated files, then write the full set atomically-ish. ---
mkdirSync(abisDir, { recursive: true });
for (const entry of readdirSync(abisDir)) {
  if (entry.endsWith(".ts") || entry === ".gitkeep") rmSync(resolve(abisDir, entry));
}
for (const [name, content] of outputs) writeFileSync(resolve(abisDir, name), content);

console.log(`  ✓ ${"index.ts".padEnd(24)}`);
console.log("Done.");
