// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit by hand.
// Merged custom errors for decoding reverts from the Iris stack.
// Protocol + venue adapters: Iris, Blm, WhitelistBlm, AaveV3Adapter, MorphoBlueAdapter.
// Dependency errors that propagate through the adapters:
//   out/SafeTransferLib.sol/SafeTransferLib.json — solady transfer/approve/permit2 errors (9 errors)
//   out/LibClone.sol/LibClone.json — solady clone (pod) deployment errors (3 errors)
//   out/Errors.sol/Errors.json — Aave V3 (aave-v3-origin) protocol errors (92 errors)
// Deduped by selector: 146 collected -> 133 unique.
// Note: Morpho Blue reverts with Error(string) (decoded natively by viem), so it has
// no custom-error ABI; Aave V3 (aave-v3-origin) uses custom errors, included above.
// Provenance: iris-core @ 22ea4d3 (solc 0.8.35+commit.47b9dedd)
// Regenerate: pnpm --filter @iris-credit/core-sdk sync:abis

export const errorsAbi = [
  {
    "type": "error",
    "name": "AclAdminCannotBeZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AdapterNotSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AddressesProviderAlreadyAdded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AddressesProviderNotRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadySet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ApproveFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AssetNotBorrowableInIsolation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AssetNotListed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BlmNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BondLltvNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BondLltvTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BorrowCapExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BorrowingNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerMustBePool",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerNotAToken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerNotAssetListingOrPoolAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerNotPoolAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerNotPoolConfigurator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerNotPoolOrEmergencyAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerNotPositionManager",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerNotRiskOrPoolAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerNotRiskOrPoolOrEmergencyAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerNotUmbrella",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CastOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CollateralCannotBeLiquidated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CollateralCannotCoverNewBorrow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CollateralTokenMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DebtCeilingExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DebtCeilingNotZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DebtTokenMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DeploymentFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EModeCategoryReserved",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ETHTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FixedRateTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FlashloanDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FlashloanPremiumInvalid",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HealthFactorLowerThanLiquidationThreshold",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HealthFactorNotBelowThreshold",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HealthyBond",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HealthyLoan",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InconsistentEModeCategory",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InconsistentFlashloanParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InconsistentParamsLength",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientBond",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientCollateral",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAddressesProvider",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAddressesProviderId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidBorrowCap",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidBurnAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidCollateralInEmode",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "categoryId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidData",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidDebtCeiling",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidDebtInEmode",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "categoryId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidDecimals",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidDuration",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidEmodeCategoryParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidExpiration",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidFlashloanExecutorReturn",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidFreezeState",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidGracePeriod",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidInterestRateModeSelected",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidLiquidationBonus",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidLiquidationProtocolFee",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidLiquidationThreshold",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidLtv",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidLtvzeroState",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMaxRate",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMintAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidNonce",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidOptimalUsageRatio",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidReserveFactor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidReserveIndex",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidReserveParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidSupplyCap",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LiquidationGraceSentinelCheckFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LoanNotCreated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LoanNotResolved",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LtvValidationFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MustBeEmodeCollateral",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "categoryId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "MustNotLeaveDust",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoDebtOfSelectedType",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoExplicitAmountToRepayOnBehalf",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoMoreReservesAllowed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAllowedVenue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBorrowableInEMode",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotContract",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotEnoughAvailableUserBalance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotMultipleOfBp",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OperationNotSupported",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OverduePeriodTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OverdueRateTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ParamsTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Permit2AmountOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Permit2ApproveFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Permit2Failed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Permit2LockdownFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PoolAddressesDoNotMatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PriceOracleSentinelCheckFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuoteExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveAlreadyAdded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveAlreadyInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveDebtNotZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveFrozen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveInactive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveLiquidityNotZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveNotInDeficit",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReservePaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SaltDoesNotStartWith",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SelfLiquidation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SignatureExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SiloedBorrowingViolation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Slope2MustBeGteSlope1",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SpecifiedCurrencyNotBorrowedByUser",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SupplyCapExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SupplyToAToken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TotalSupplyQueryFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFromFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnderlyingBalanceZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnderlyingCannotBeRescued",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnderlyingClaimableRightsNotZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UserCannotHaveDebt",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UserInIsolationModeOrLtvZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VariableDebtSupplyNotZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VenueIdTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WithdrawToAToken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddressNotValid",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
] as const;
